spring:
  application:
    name: report
  data:
    mongodb:
      uri: mongodb://jogyoungjun:131072@ec2-13-208-253-99.ap-northeast-3.compute.amazonaws.com:27017/research_db
jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2